apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    server: web
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      server: web
  template:
    metadata:
      labels:
        app: nginx
        server: web
    spec:
      containers:
      - image: nginx
        name: nginx
